modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"

[[mods]]
modId = "equipmentbenediction"
version = "${file.jarVersion}"
displayName = "EquipmentBenediction"
authors = "XiaoHuNao"
description = '''
Add quality affixes to equipment through data packets
'''